language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - coverage run --omit "*test*" --source=bot_ross -m unittest discover bot_ross
after_success:
  - coveralls
